"""add users table

Revision ID: 43774c187998
Revises: 
Create Date: 2021-05-13 23:02:21.903310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43774c187998'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
