"""update product model

Revision ID: 4491feeecdec
Revises: 24fbe3357f8a
Create Date: 2021-05-22 17:33:24.047056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4491feeecdec'
down_revision = '24fbe3357f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gino_admin_users')
    op.drop_table('gino_admin_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gino_admin_history',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('route', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('log_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('object_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gino_admin_history_pkey')
    )
    op.create_table('gino_admin_users',
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('login', name='gino_admin_users_pkey')
    )
    # ### end Alembic commands ###
