"""update users table

Revision ID: 7967edfd9f18
Revises: 50de39b69cb9
Create Date: 2021-05-15 16:36:26.475870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7967edfd9f18'
down_revision = '50de39b69cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
