"""update product model 2

Revision ID: e7abfa02496c
Revises: 4491feeecdec
Create Date: 2021-05-22 17:35:05.773245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7abfa02496c'
down_revision = '4491feeecdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
