"""update products table

Revision ID: fb488e2be728
Revises: e7abfa02496c
Create Date: 2021-05-25 15:46:52.654960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb488e2be728'
down_revision = 'e7abfa02496c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gino_admin_users')
    op.drop_table('gino_admin_history')
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('product', 'date_added')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.create_table('gino_admin_history',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('route', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('log_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('object_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gino_admin_history_pkey')
    )
    op.create_table('gino_admin_users',
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('login', name='gino_admin_users_pkey')
    )
    # ### end Alembic commands ###
