"""update users table

Revision ID: 0508f9ca0879
Revises: 43774c187998
Create Date: 2021-05-14 14:40:38.539453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0508f9ca0879'
down_revision = '43774c187998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
